In [1]:
import pandas as pd
import numpy as np

data = {
"OrderID": [101, 102, 103, 104, 105, 106, 107, 108],
"Customer": ["Alice", "Bob", "Alice", "David", "Eva", "Bob", "Frank", "Eva"],
"Product": ["Laptop", "Phone", "Mouse", "Laptop", "Tablet", "Phone", "Tablet", "Mouse"],
"Category": ["Electronics", "Electronics", "Accessories", "Electronics", "Electronics", "Electronics", "Electronics", "Accessories"],
"Quantity": [1, 2, 3, 1, 2, 1, 1, 4],
"Price": [1200, 800, 25, 1200, 600, 800, 600, np.nan]
}

df = pd.DataFrame(data)

In [2]:
1. Show the first 5 rows.
2. How many total orders are there?
3. Show all orders where the product is "Laptop".
4. What is the total revenue for each order? (Hint: can create a new column)
5. How many missing values exist in the dataset?
6. What is the total revenue per product?
7. What is the total revenue per customer?
8. What is the average quantity ordered per category?
9. Which customer placed the most total quantity of items?
10. Fill missing Price values with the average price of that product.
11. Create a new column called `"High_Value_Order"`:
    1. Revenue > 1500 ? "Yes"
    2. Otherwise ? "No"
12. For each category, calculate:
    - Total revenue
    - Number of orders
    - Average order revenue
13. Identify customers whose total spending is above the overall average customer spending.
14. Which category has the highest revenue per order (Revenue / Number of Orders)?

SyntaxError: invalid syntax (<ipython-input-2-b273be0b771c>, line 1)

In [4]:
df.head(5)

   OrderID Customer Product     Category  Quantity   Price
0      101    Alice  Laptop  Electronics         1  1200.0
1      102      Bob   Phone  Electronics         2   800.0
2      103    Alice   Mouse  Accessories         3    25.0
3      104    David  Laptop  Electronics         1  1200.0
4      105      Eva  Tablet  Electronics         2   600.0

In [5]:
df["OrderID"].nunique()

8

In [6]:
df[df["Product"] == "Laptop"]

   OrderID Customer Product     Category  Quantity   Price
0      101    Alice  Laptop  Electronics         1  1200.0
3      104    David  Laptop  Electronics         1  1200.0

In [8]:
df["TotalRevenue"] = df["Quantity"] * df["Price"]
df

   OrderID Customer Product     Category  Quantity   Price  TotalRevenue
0      101    Alice  Laptop  Electronics         1  1200.0        1200.0
1      102      Bob   Phone  Electronics         2   800.0        1600.0
2      103    Alice   Mouse  Accessories         3    25.0          75.0
3      104    David  Laptop  Electronics         1  1200.0        1200.0
4      105      Eva  Tablet  Electronics         2   600.0        1200.0
5      106      Bob   Phone  Electronics         1   800.0         800.0
6      107    Frank  Tablet  Electronics         1   600.0         600.0
7      108      Eva   Mouse  Accessories         4     NaN           NaN

In [12]:
df.isna().sum().sum()

2

In [14]:
df.groupby("Product")["TotalRevenue"].sum().reset_index()

  Product  TotalRevenue
0  Laptop        2400.0
1   Mouse          75.0
2   Phone        2400.0
3  Tablet        1800.0

In [15]:
df.groupby("Customer")["TotalRevenue"].sum().reset_index()

  Customer  TotalRevenue
0    Alice        1275.0
1      Bob        2400.0
2    David        1200.0
3      Eva        1200.0
4    Frank         600.0

In [17]:
df.groupby("Category")["TotalRevenue"].mean().reset_index()

      Category  TotalRevenue
0  Accessories          75.0
1  Electronics        1100.0

In [26]:
df.groupby("Customer")["Quantity"].sum().sort_values(ascending=False).head(1).reset_index()

  Customer  Quantity
0      Eva         6

In [34]:
df["Price"] = df["Price"].fillna(df.groupby("Product")["Price"].transform("mean"))
df

   OrderID Customer Product     Category  Quantity   Price  TotalRevenue
0      101    Alice  Laptop  Electronics         1  1200.0        1200.0
1      102      Bob   Phone  Electronics         2   800.0        1600.0
2      103    Alice   Mouse  Accessories         3    25.0          75.0
3      104    David  Laptop  Electronics         1  1200.0        1200.0
4      105      Eva  Tablet  Electronics         2   600.0        1200.0
5      106      Bob   Phone  Electronics         1   800.0         800.0
6      107    Frank  Tablet  Electronics         1   600.0         600.0
7      108      Eva   Mouse  Accessories         4    25.0           NaN

In [36]:
df["High_Value_Order"] = np.where(df["TotalRevenue"] > 1500, "Yes", "No")
df

,OrderID,Customer,Product,Category,Quantity,Price,TotalRevenue,High_Value_Order
0,101,Alice,Laptop,Electronics,1,1200.0,1200.0,No
1,102,Bob,Phone,Electronics,2,800.0,1600.0,Yes
2,103,Alice,Mouse,Accessories,3,25.0,75.0,No
3,104,David,Laptop,Electronics,1,1200.0,1200.0,No
4,105,Eva,Tablet,Electronics,2,600.0,1200.0,No
5,106,Bob,Phone,Electronics,1,800.0,800.0,No
6,107,Frank,Tablet,Electronics,1,600.0,600.0,No
7,108,Eva,Mouse,Accessories,4,25.0,NaN,No

In [41]:
customer_spend = df.groupby("Customer")["TotalRevenue"].sum()

In [40]:
df.groupby("Customer")["TotalRevenue"].sum().mean()

1335.0

In [42]:
customer_spend

Customer
Alice    1275.0
Bob      2400.0
David    1200.0
Eva      1200.0
Frank     600.0
Name: TotalRevenue, dtype: float64

In [43]:
customer_spend[customer_spend > df.groupby("Customer")["TotalRevenue"].sum().mean()]

Customer
Bob    2400.0
Name: TotalRevenue, dtype: float64